PROGRAM TESTMODELPARSER

  ! TEST INPUTTING THE MODEL FROM FILE USING MODEL_MANAGER MODULE

  USE MODELMODULE
  IMPLICIT NONE

  TYPE (CME_MODEL) :: MODEL, MODEL2

  INTEGER :: I, J, R
  DOUBLE PRECISION :: P1, P2, ERROR

  CALL MODEL%LOAD('MODELS/TOGGLE_TEST_MODEL.INPUT')

  CALL MODEL%RESET_PARAMETERS((/5000.0D0, 1600.D0, 1.0D0, 1.0D0/))

  WRITE (*,*) 'MODEL LOADED.'
  WRITE (*,*) 'NUMBER OF SPECIES: ',MODEL%NSPECIES
  WRITE (*,*) 'SPECIES NAMES: ', MODEL%SPECIES_NAMES
  WRITE (*,*) 'NUMBER OF PARAMETERS:', MODEL%NPARAMETERS
  WRITE (*,*) 'PARAMETER VALUES:', MODEL%PARAMETER_VAL
  WRITE (*,*) 'STOICHIOMETRY:'
  DO I = 1,MODEL%NSPECIES
     DO J = 1, MODEL%NREACTIONS
        WRITE (*,FMT = '(I2 4X)',ADVANCE='NO') MODEL%STOICHIOMETRY(I,J)
     ENDDO
     WRITE (*,*) ''
  END DO


  ERROR = 0.0D0
  ! NOW TEST THE ACCURACY OF THE READ-FROM-FILE PROPENSITIES
  DO I = 1, 50
     DO J = 1,50
        DO R = 1, MODEL%NREACTIONS
           P1 = PROP((/ I, J /), R, (/0D0 , 0D0/))
           P2 = MODEL%PROPENSITY((/I, J/), R)
           ERROR = ERROR + ABS(P1-P2)
           WRITE (*, 201) I, J, R, P1, P2, ABS(P1-P2)
201        FORMAT (1X, 'IE=', I4,2X, 'J=', I4, 2X, 'R=',I4,2X, 'P1=', E9.2, 2X, 'P2=', E9.2, 2X, '|P2-P1|=',E9.2)
        ENDDO
     ENDDO
  ENDDO

  PRINT*,'PROPENSITY TESTING COMPLETED FOR MODEL 1. ACCUMULATED ERROR = ',ERROR


  CALL MODEL2%LOAD('MODELS/TOGGLE_TEST_MODEL.INPUT')
  CALL MODEL2%RESET_PARAMETERS((/5000.0D0, 1600.D0, 1.0D0, 1.0D0/))

  WRITE (*,*) 'MODEL LOADED.'
  WRITE (*,*) 'NUMBER OF SPECIES: ',MODEL2%NSPECIES
  WRITE (*,*) 'SPECIES NAMES: ', MODEL2%SPECIES_NAMES
  WRITE (*,*) 'NUMBER OF PARAMETERS:', MODEL2%NPARAMETERS
  WRITE (*,*) 'PARAMETER VALUES:', MODEL2%PARAMETER_VAL
  WRITE (*,*) 'STOICHIOMETRY:'
  DO I = 1,MODEL2%NSPECIES
     DO J = 1, MODEL2%NREACTIONS
        WRITE (*,FMT = '(I2 4X)',ADVANCE='NO') MODEL2%STOICHIOMETRY(I,J)
     ENDDO
     WRITE (*,*) ''
  END DO
  MODEL2%CUSTOMPROP=>PROP
  ERROR = 0.0D0
  ! NOW TEST THE ACCURACY OF THE READ-FROM-FILE PROPENSITIES
  DO I = 1, 50
     DO J = 1,50
        DO R = 1, MODEL2%NREACTIONS
           P1 = PROP( (/I, J /),R)
           P2 = MODEL2%PROPENSITY((/I, J/), R)
           ERROR = ERROR + ABS(P1-P2)
           WRITE (*, 201) I, J, R, P1, P2, ABS(P1-P2)
        ENDDO
     ENDDO
  ENDDO

  PRINT*,'PROPENSITY TESTING COMPLETED FOR MODEL 2. ACCUMULATED ERROR = ',ERROR

CONTAINS
  DOUBLE PRECISION FUNCTION PROP(STATE, REACTION, PARAMETERS)
    ! PROPENSITY FUNCTION FOR THE TOGGLE SWITCH MODEL
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: STATE(:), REACTION
    DOUBLE PRECISION, INTENT(IN), OPTIONAL :: PARAMETERS(:)
    DOUBLE PRECISION C
    !------GENERATE INDIVIDUAL VALUES OF PROPENSITY FUNCTIONS--
    !----------------------------------------------------------
    SELECT CASE (REACTION)
    CASE (1)
       C=5000.0D0
       PROP=C/(1.0D0+DBLE(STATE(2))**(2.5D0))
    CASE (2)
       C=1600.0D0
       PROP=C/(1.0D0+DBLE(STATE(1))**(1.5D0))
    CASE (3)
       C=1.0D0*DBLE(STATE(1))
       PROP=C
    CASE (4)
       C=1.0D0*DBLE(STATE(2))
       PROP=C
    END SELECT
  END FUNCTION PROP

END
