MODULE MODELMODULE
  ! THIS MODULE WILL DEFINE THE 'CLASS' OF CME MODELS IN FORTRAN
  USE FORTRANPARSER
  IMPLICIT NONE

  INTERFACE
     DOUBLE PRECISION FUNCTION PROPFUNC(STATE, REACTION, PARAMETERS)
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: STATE(:), REACTION
       DOUBLE PRECISION, INTENT(IN), OPTIONAL :: PARAMETERS(:)
     END FUNCTION PROPFUNC
  END INTERFACE

  TYPE :: CME_MODEL
     ! MODEL NEEDS TO BE LOADED BEFORE WE DO ANYTHING ELSE
     LOGICAL :: LOADED = .FALSE.
     ! NUMBERS OF SPECIES, REACTIONS, AND UNCERTAIN PARAMETERS
     INTEGER :: NSPECIES
     INTEGER :: NREACTIONS
     INTEGER :: NPARAMETERS

     DOUBLE PRECISION, DIMENSION (:), ALLOCATABLE :: PARAMETER_VAL

     ! STOICHIOMETRY MATRIX, STORED IN DENSE FORMAT, EACH COLUMN CORRESPONDS TO ONE REACTION
     INTEGER, DIMENSION (:, :), ALLOCATABLE :: STOICHIOMETRY

     CHARACTER (LEN = 20), ALLOCATABLE, DIMENSION (:) :: SPECIES_NAMES, PARAMETER_NAMES
     ! PRIVATE ATTRIBUTE, THE EQUATIONPARSER TYPE STOR\ES THE BYTE CODE TO
     ! COMPUTE PROPENSITY FUNCTIONS
     TYPE (EQUATIONPARSER), DIMENSION(:), ALLOCATABLE, PRIVATE :: PROPPARSER
     PROCEDURE (PROPFUNC), POINTER, NOPASS :: CUSTOMPROP

   CONTAINS
     PROCEDURE :: CREATE

     PROCEDURE :: LOAD

     PROCEDURE :: RESET_PARAMETERS

     PROCEDURE :: PROPENSITY => PROPENSITY_BUILTIN

  END TYPE CME_MODEL

CONTAINS

  SUBROUTINE CREATE(THIS, N_SPECIES, N_REACTIONS, N_PARAMETERS)
    IMPLICIT NONE
    CLASS(CME_MODEL) :: THIS
    INTEGER :: N_SPECIES
    INTEGER :: N_REACTIONS
    INTEGER :: N_PARAMETERS

    THIS%NSPECIES = N_SPECIES
    THIS%NREACTIONS = N_REACTIONS
    THIS%NPARAMETERS = N_PARAMETERS
    ALLOCATE(THIS%STOICHIOMETRY(N_SPECIES, N_REACTIONS), THIS%PARAMETER_VAL(N_PARAMETERS))
  END SUBROUTINE CREATE

  SUBROUTINE LOAD(THIS, FILENAME)
    ! PURPOSE:
    ! ========
    ! LOAD THE MODEL FROM FILE
    !
    ! USAGE:
    ! ======
    !        CALL MODEL%LOAD(<FILENAME>)
    !        THE VARIABLE FILENAME IS OPTIONAL
    IMPLICIT NONE

    CLASS (CME_MODEL) :: THIS
    CHARACTER (LEN = *), OPTIONAL :: FILENAME

    CHARACTER (LEN = 400) :: ICHAR
    CHARACTER (LEN = 200) :: FSTRING
    CHARACTER (LEN = 20), ALLOCATABLE, DIMENSION (:) :: FVAR

    LOGICAL :: NSPECIES_READ = .FALSE., NREACTIONS_READ = .FALSE., NPARAM_READ = .FALSE., &
         PARAMETERS_READ = .FALSE., SPECIES_NAMES_READ = .FALSE., &
         PARAM_NAMES_READ = .FALSE.

    INTEGER :: I, IOS

    IF (PRESENT(FILENAME)) THEN
       OPEN(UNIT = 10, FILE = FILENAME, IOSTAT = IOS, STATUS = "OLD", ACTION = "READ")
       IF (IOS /= 0) STOP "ERROR OPENING FILE "
    ELSE
       OPEN(UNIT = 10, FILE = 'MODEL.INPUT', IOSTAT = IOS, STATUS = "OLD", ACTION = "READ")
       IF (IOS /= 0) STOP "ERROR OPENING FILE "
    ENDIF

    FILE_SCAN : DO
       READ(10, FMT = *, IOSTAT = IOS) ICHAR
       IF (IOS /= 0) EXIT

       IF (ICHAR == 'NSPECIES') THEN
          READ(10, FMT = *, IOSTAT = IOS) THIS%NSPECIES
          NSPECIES_READ = .TRUE.
       ENDIF

       IF (ICHAR == 'NREACTIONS') THEN
          READ(10, FMT = *, IOSTAT = IOS) THIS%NREACTIONS
          NREACTIONS_READ = .TRUE.
       ENDIF

       IF (ICHAR == 'NPARAMETERS') THEN
          READ(10, FMT = *, IOSTAT = IOS) THIS%NPARAMETERS
          NPARAM_READ = .TRUE.
       ENDIF

       IF (ICHAR == 'SPECIES') THEN
          ALLOCATE(THIS%SPECIES_NAMES(THIS%NSPECIES))
          DO I = 1, THIS%NSPECIES
             READ(10, FMT = *, IOSTAT = IOS) THIS%SPECIES_NAMES(I)
          ENDDO
          SPECIES_NAMES_READ = .TRUE.
       ENDIF

       !      READ THE REACTIONS
       IF (ICHAR == 'REACTIONS') THEN
          IF (.NOT.SPECIES_NAMES_READ) STOP 'MODEL INPUT ERROR: REACTIONS STATED BEFORE SPECIES NAMES ARE DECLARED.'
          IF (.NOT.NSPECIES_READ) STOP 'MODEL INPUT ERROR: NUMBER OF SPECIES NOT DECLARED.'
          IF (.NOT.NREACTIONS_READ) STOP 'MODEL INPUT ERROR: NUMBER OF REACTIONS NOT DECLARED.'
          IF (.NOT.ALLOCATED(THIS%STOICHIOMETRY)) ALLOCATE(THIS%STOICHIOMETRY(THIS%NSPECIES, THIS%NREACTIONS))
          DO I = 1, THIS%NREACTIONS
             READ(10, FMT = '(A)', IOSTAT = IOS) ICHAR
             CALL STOICH_INPUT(THIS%NSPECIES, THIS%STOICHIOMETRY(1:THIS%NSPECIES, I), ICHAR, THIS%SPECIES_NAMES)
          ENDDO
       ENDIF

       IF (ICHAR == 'PARAMETERS') THEN
          IF (.NOT.NPARAM_READ) STOP 'MODEL INPUT ERROR: NUMBER OF PARAMETERS NOT DECLARED BEFORE SPECIFYING PARAMETER NAMES.'
          ALLOCATE(THIS%PARAMETER_NAMES(THIS%NPARAMETERS), THIS%PARAMETER_VAL(THIS%NPARAMETERS))
          DO I = 1, THIS%NPARAMETERS
             READ(10, FMT = *, IOSTAT = IOS) THIS%PARAMETER_NAMES(I)
          ENDDO
          PARAM_NAMES_READ = .TRUE.
       ENDIF

       !     READ THE PROPENSITY FUNCTIONS, THE STRINGS OF MATHEMATICAL EXPRESSIONS HAVE TO BE LISTED IN THE SAME ORDER AS THE REACTIONS
       IF (ICHAR == 'PROPENSITIES') THEN
          IF ((SPECIES_NAMES_READ.EQV..FALSE.).OR.(PARAM_NAMES_READ.EQV..FALSE.)) THEN
             STOP 'MODEL INPUT ERROR: PROPENSITIES SPECIFIED BEFORE ALL SPECIES AND PARAMETERS ARE NAMED.'
          ELSE
             ALLOCATE(FVAR(THIS%NSPECIES + THIS%NPARAMETERS))
             ALLOCATE(THIS%PROPPARSER(THIS%NREACTIONS))
             DO I = 1, THIS%NSPECIES
                FVAR (I) = TRIM(THIS%SPECIES_NAMES(I))
             ENDDO
             DO I = 1, THIS%NPARAMETERS
                FVAR (THIS%NSPECIES + I) = TRIM(THIS%PARAMETER_NAMES(I))
             ENDDO
             DO I = 1, THIS%NREACTIONS
                READ(10, FMT = '(A)', IOSTAT = IOS) FSTRING
                THIS%PROPPARSER(I) = EQUATIONPARSER(TRIM(FSTRING), FVAR)
             ENDDO
          ENDIF
       ENDIF
    ENDDO FILE_SCAN
    CLOSE (10)
    THIS%LOADED = .TRUE.
  END SUBROUTINE LOAD
  !-----------------------------------------------------------------------------|
  DOUBLE PRECISION FUNCTION PROPENSITY_BUILTIN(THIS, STATE, REACTION)
    ! PURPOSE:
    ! ========
    ! INTERFACE TO COMPUTE THE PROPENSITY BASED ON THE STRING EXPRESSION
    ! IN THE MODEL INPUT FILE.
    !
    ! HOW TO USE:
    ! ==========
    ! Y = MODEL%PROPENSITY(STATE, REACTION)
    !
    ! ARGUMENTS:
    ! =========
    ! STATE         : ARRAY STORING THE STATE
    ! REACTION      : INTEGER STORING THE REACTION INDEX
    !

    IMPLICIT NONE

    CLASS (CME_MODEL), INTENT(IN) :: THIS
    INTEGER, INTENT(IN) :: STATE(:)
    INTEGER, INTENT(IN) :: REACTION

    DOUBLE PRECISION, DIMENSION(THIS%NSPECIES + THIS%NPARAMETERS) :: FVAL
    INTEGER I, N

    IF (ASSOCIATED(THIS%CUSTOMPROP)) THEN
       PROPENSITY_BUILTIN = THIS%CUSTOMPROP(STATE(1:THIS%NSPECIES), REACTION, THIS%PARAMETER_VAL(1:THIS%NPARAMETERS))
    ELSE
       N = THIS%NSPECIES
       DO I = 1, THIS%NSPECIES
          FVAL(I) = DBLE(STATE(I))
       ENDDO
       FVAL(THIS%NSPECIES + 1:THIS%NSPECIES + THIS%NPARAMETERS) = THIS%PARAMETER_VAL(1:THIS%NPARAMETERS)
       PROPENSITY_BUILTIN = THIS%PROPPARSER(REACTION)%EVALUATE(FVAL)
    ENDIF

  END FUNCTION PROPENSITY_BUILTIN
  !-----------------------------------------------------------------------------|
  SUBROUTINE RESET_PARAMETERS(THIS, PVAL)
    ! PURPOSE:
    ! ========
    ! RESET THE VALUES OF THE UNCERTAIN PARAMETERS IN THE STOCHASTIC CHEMICAL KINETICS MODEL.
    !
    ! HOW TO USE:
    ! ===========
    ! THE COMMAND
    !           CALL MODEL%RESET_PARAMETERS(X)
    ! WILL RESET THE PARAMETER VALUES IN THE MODEL TO THE VALUES IN THE ARRAY X
    IMPLICIT NONE
    CLASS (CME_MODEL) :: THIS
    DOUBLE PRECISION, DIMENSION (:) :: PVAL

    THIS%PARAMETER_VAL(1:THIS%NPARAMETERS) = PVAL(1:THIS%NPARAMETERS)

  END SUBROUTINE RESET_PARAMETERS
  !-----------------------------------------------------------------------------|
  SUBROUTINE STOICH_INPUT(NSPECIES, STOICH_VEC, STR, SPECIES_NAMES)

    !   PURPOSE:
    !   =======
    !   OUTPUT THE STOICHIOMETRY VECTOR OF THE REACTION GIVEN ITS STRING EXPRESSION
    !
    IMPLICIT NONE
    INTEGER, INTENT (INOUT) :: STOICH_VEC(*)
    INTEGER, INTENT(IN) :: NSPECIES
    CHARACTER(LEN = *), INTENT(IN) :: STR
    CHARACTER(LEN = *), DIMENSION(NSPECIES), INTENT(IN) :: SPECIES_NAMES


    !   INTERNAL VARIABLES
    CHARACTER(LEN = 200), DIMENSION(100) :: TERMS       ! SUPPORTING UP TO 100 REACTANTS+PRODUCTS
    CHARACTER(LEN = 50) :: WORD = ''
    INTEGER :: DIR = 0       ! DIRECTION OF THE ARROW , 1 IF "->", 2 IF "<-", IF 0 THEN UNSPECIFIED.
    INTEGER :: ELL, I, NTERMS, NLEFT, COEFF, K, J
    LOGICAL :: DEFINED = .FALSE.

    NTERMS = 0
    NLEFT = 0

    WORD = ''

    STOICH_VEC(1:NSPECIES) = 0
    ELL = LEN(TRIM(STR))
    STRING_SCAN : DO I = 1, ELL
       WORD = TRIM(WORD) // STR(I:I)
       IF (STR(I:I) == ' ' .OR. I == ELL) THEN
          WORD = ADJUSTL(WORD);
          IF (TRIM(WORD) == '->') THEN
             DIR = 1
             NLEFT = NTERMS ! NUMBER OF TERMS ON THE LEFT SIDE OF THE EQUATION
          ELSEIF (TRIM(WORD) == '<-') THEN
             DIR = 2
             NLEFT = NTERMS ! NUMBER OF TERMS ON THE LEFT SIDE OF THE EQUATION
          ELSEIF (TRIM(WORD) /= '+') THEN
             NTERMS = NTERMS + 1
             TERMS(NTERMS) = TRIM(WORD)
          ENDIF
          WORD = ''
       ENDIF
    END DO STRING_SCAN

    IF (DIR==0) THEN
       STOP 'SYNTAX ERROR IN CHEMICAL REACTION, ONLY ONE SIDE WAS WRITTEN.'
    ENDIF

    ! PROCESSING THE TERMS OF THE REACTION EQUATION, READ THEIR COEFFICIENTS TO THE STOICHIOMETRY VECTOR
    DO I = 1, NTERMS
       WRITE(*, *) TERMS(I)
       IF (TERMS(I) /= '0') THEN
          DO J = 1, NSPECIES
             WORD = TERMS(I)
             K = INDEX(TERMS(I), TRIM(SPECIES_NAMES(J)))
             DEFINED = DEFINED .OR. (K/=0)
             IF (K==0) THEN
                COEFF = 0
             ELSEIF (WORD(K:LEN(TRIM(WORD)))==TRIM(SPECIES_NAMES(J))) THEN
                IF (K > 1) THEN
                   READ(WORD(1:K - 1), *) COEFF
                ELSEIF (K == 1) THEN
                   COEFF = 1
                ENDIF
             ENDIF
             IF (I <= NLEFT) THEN
                STOICH_VEC(J) = STOICH_VEC(J) - COEFF
             ELSE
                STOICH_VEC(J) = STOICH_VEC(J) + COEFF
             ENDIF
          ENDDO
          IF (.NOT.DEFINED) WRITE(*, *) 'WARNING: SPECIES ', TERMS(I), ' NOT DEFINED IN THE MODEL.'
       ENDIF
    END DO

    IF (DIR == 2) STOICH_VEC(1:NSPECIES) = -1 * STOICH_VEC(1:NSPECIES)

  END SUBROUTINE STOICH_INPUT

END MODULE MODELMODULE
