! CREATED BY ${USER_NAME} ON 11/27/18.

PROGRAM SOLVE_REPRESS
  !     SOLVE CME OF THE REPRESSILATOR
  USE STATESPACE
  USE KRYLOVSOLVER
  IMPLICIT NONE

  INTERFACE
     DOUBLE PRECISION FUNCTION CLOCK()
     END FUNCTION CLOCK
  END INTERFACE

  DOUBLE PRECISION :: T = 10.0D0, EXP_TOL = 1.0D-14, FSP_TOL = 1.0D-4
  TYPE (CME_MODEL) :: MODEL
  TYPE (FINITE_STATE_PROJECTION) :: FSP_IN, FSP
  DOUBLE PRECISION, DIMENSION(NMAX) :: P0, P
  DOUBLE PRECISION :: TIC
  INTEGER :: I

  CALL RANDOM_SEED()

  CALL MODEL%CREATE(3, 6, 3)
  MODEL%STOICHIOMETRY = RESHAPE((/1,0,0,-1,0,0,0,1,0,0,-1,0,0,0,1,0,0,-1/), (/3,6/))
  MODEL%CUSTOMPROP => PROPENSITY
  CALL MODEL%RESET_PARAMETERS([100.0D0, 25.0D0, 1.0D0])
  MODEL%LOADED = .TRUE.

  ! INITIALIZE THE ATTRIBUTES OF THE FSP BASED ON THE UNDERLYING MODEL
  TIC = CLOCK()
  WRITE(*,*) 'ALLOCATING MEMORY FOR THE FSP...'
  CALL FSP_IN%CREATE(MODEL)
  CALL FSP%CREATE(MODEL)
  WRITE(*, FMT = 200) CLOCK() - TIC

  FSP_IN%SIZE = 1
  FSP_IN%STATE(:, 1) = [22, 0, 0]
  P0(1) = 1.0
  FSP_IN%VECTOR = P0
  FSP = FSP_IN
  TIC = CLOCK()
  WRITE(*,*) 'CALLING THE SOLVER...'
  CALL CME_SOLVE(MODEL, T, FSP_IN, FSP, FSP_TOL, EXP_TOL, VERBOSITY = 1)
  WRITE(*, FMT = 200) CLOCK() - TIC
200 FORMAT ('ELAPSED TIME :', F10.2)

  CALL FSP%CLEAR()
  CALL FSP_IN%CLEAR()
CONTAINS
  DOUBLE PRECISION FUNCTION PROPENSITY(STATE, REACTION, PARAMETERS)
    INTEGER, INTENT(IN) :: STATE(:), REACTION
    DOUBLE PRECISION, INTENT(IN), OPTIONAL :: PARAMETERS(:)

    SELECT CASE (REACTION)
    CASE(1)
       PROPENSITY = PARAMETERS(1)/(1D0 + PARAMETERS(2)*STATE(2)**6.0D0)
    CASE(2)
       PROPENSITY = PARAMETERS(3)*STATE(1)
    CASE(3)
      PROPENSITY = PARAMETERS(1)/(1D0 + PARAMETERS(2)*STATE(3)**6.0D0)
    CASE(4)
      PROPENSITY = PARAMETERS(3)*STATE(2)
    CASE(5)
      PROPENSITY = PARAMETERS(1)/(1D0 + PARAMETERS(2)*STATE(1)**6.0D0)
    CASE(6)
      PROPENSITY = PARAMETERS(3)*STATE(3)

    END SELECT
  END FUNCTION PROPENSITY
END PROGRAM
